export const MAIN_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const REGISTER_ROUTE = '/register'
export const PROFILE_ROUTE = '/profile'
export const TRANSACTIONS_ROUTE = '/transactions'
export const TRANSFER_ROUTE = '/transfer'
export const DEPOSIT_ROUTE = '/deposit'
export const OPENING_DEPOSIT_ROUTE = '/open-deposit'